# Generated by Django 3.1.3 on 2020-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20201123_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
