# Generated by Django 3.1.3 on 2020-11-23 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0007_auto_20201123_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='users_likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
